[package]
name = "catch_client"
version = "0.1.0"
authors = [
    "leod <subtle.frustration@proton.me>"
]

[dependencies]
log = "*"
env_logger = "*"
piston = "*"
piston_window = "0.20.0"
piston2d-graphics = "0.9.0"
pistoncore-glutin_window = "0.12.0"
piston2d-opengl_graphics = "0.12.0"
gl = "0.0.12"
#ecs = "*"
time = "0.1.32"
getopts = "0.2.14"
rand = "0.3.11"
cpal = "*"
#rodio = "*"

[dependencies.rodio]
git = "https://github.com/tomaka/rodio.git"

[dependencies.ecs]
git = "https://github.com/HeroesGrave/ecs-rs.git"

[dependencies.color]
git = "https://github.com/bjz/color-rs.git"

[dependencies.catch_shared]
path = "../catch_shared"

[dependencies.renet]
path = "../../renet"

[dependencies.cereal]
path = "../../cereal"

[dependencies.image]
version = "*"
features = ["png_codec"]
