[package]
name = "catch_client"
version = "0.1.0"
authors = [
    "leod <subtle.frustration@proton.me>"
]

[dependencies]
piston = "0.9.0"
piston2d-graphics = "0.4.1"
pistoncore-glutin_window = "0.11.0"
piston2d-opengl_graphics = "0.6.0"
gl = "0.0.12"
#ecs = "*"
time = "0.1.32"

[dependencies.ecs]
git = "https://github.com/HeroesGrave/ecs-rs.git"

[dependencies.catch_shared]
path = "../catch_shared"

[dependencies.renet]
path = "../../renet"

[dependencies.cereal]
path = "../../cereal"

[dependencies.image]
version = "*"
features = ["png_codec"]
